"""Add rf_label column to alerts table

Revision ID: add_rf_label_20260411
Revises: (latest existing migration)
Create Date: 2026-04-11 00:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_rf_label_20260411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('rf_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'rf_label')
    # ### end Alembic commands ###
